### ISSUE TITLE
Fehlerteufelchen is sometimes clipped and is missing from printout

### ISSUE THREAD

**Issue by mist64** [mist64/64er-magazin.de#3]

**Comment by ellduin** [comment]
<img width="541" alt="web_before1" src="https://github.com/mist64/64er-magazin.de/assets/772311/500eda2e-890a-4f7a-a761-c3cf0e5e3f55">
<img width="492" alt="print_before" src="https://github.com/mist64/64er-magazin.de/assets/772311/3d7d3efc-89a7-4a96-b52b-c8d9f203af94">

Web and Print before

**Comment by ellduin** [comment]
<img width="981" alt="print_after" src="https://github.com/mist64/64er-magazin.de/assets/772311/70131e29-b076-4b13-a8bc-65a530917e9f">
<img width="884" alt="web_after1" src="https://github.com/mist64/64er-magazin.de/assets/772311/cf963777-07a0-4094-98f7-31cf05fddb15">
<img width="539" alt="web_after2" src="https://github.com/mist64/64er-magazin.de/assets/772311/52be2b57-5bd6-4528-932e-dc42ddbb4d2f">
<img width="556" alt="web_after3" src="https://github.com/mist64/64er-magazin.de/assets/772311/3795efc5-d654-4233-8522-9d7f6958e76f">
<img width="546" alt="web_after4" src="https://github.com/mist64/64er-magazin.de/assets/772311/ef2d7de5-dfde-4a4c-9e92-a9f1e7f66958">

Web and Print after
