### ISSUE TITLE
Make articles show up on Google with a date

### ISSUE THREAD

**Issue by mist64** [mist64/64er-magazin.de#85]
All articles are kind of news articles, which typically have a date when shown in Google search results. We should add whatever metadata is necessary.

**Comment by ellduin** [comment]
original date or 2024 date?

**Comment by mist64** [comment]
Original date!

**Comment by ellduin** [comment]
https://developers.google.com/search/docs/appearance/structured-data/article

**Comment by ellduin** [comment]
https://schema.org/Article

**Comment by ellduin** [comment]
maybe use this for reference later 

https://www.computerwoche.de/article/2858766/fernmeldeverordnung-zunaechst-btx-basis.html

**Comment by ellduin** [comment]
see #53

**Comment by ellduin** [comment]
https://search.google.com/test/rich-results
