### ISSUE TITLE
Move all work into `main`, don't use branches any more

### ISSUE THREAD

**Issue by mist64** [mist64/64er-magazin.de#96]
With many issues in flight, branches are hard to manage. It would be much nicer if everything was on `main`.

* Merge all future branches into main
* Change the script to only pick up issues with a release date in the past.
* Add an option to pick up all issues in the future.
* For uploading, if we pick future issues, the upload should go into the "test" subdirectory on the server.
* The feature to upload into `test/<branchname>` if the current branch is not `main` should stay so we can try experimental changes (e.g. to the script)

**Comment by thierer** [comment]
While I agree that it's sometimes cumbersome to have each issue in a separate branch, I still find it useful to have a separate branch for release work.

How about having one separate branch for future issues and then for every release merge the relevant parts into `main` from there in one, squashed commit ?

**Comment by mist64** [comment]
> How about having one separate branch for future issues and then for every release merge the relevant parts into main from there in one, squashed commit ?

I would like to keep the history of every small edit. I find it especially important to be able to track the history of listings, sometimes the commit messages have important context.

**Comment by thierer** [comment]
> > How about having one separate branch for future issues and then for every release merge the relevant parts into main from there in one, squashed commit ?
> 
> I would like to keep the history of every small edit. I find it especially important to be able to track the history of listings, sometimes the commit messages have important context.

Sure, I agree, but they would still be documented in the development branch but without clobbering the `main` branch?

For every release you'd do something like (maybe over-simplified, I'm not sure if just adding a subdir to `issues` is enough for `generate.py` to pick it up).

```
git checkout main
git checkout future_issues "issues/yyxx/*"
git commit -m "New issue xx/yy"
```

Which wouldn't affect the `future_issues` branch and its commits at all. If you'd like to document the commit in the development branch from which the new `main` commit originated, you could just do that in the commit message. (With some effort or git trickery you could also craft a "merge" commit which includes only the relevant files for the new issue, but I'd consider that confusing, as it isn't really a merge).

**Comment by mist64** [comment]
This would still not give me a detailed `git log` or `git blame` (with the whole history) for a file on main, would it?

**Comment by thierer** [comment]
No, not as convenient, if the file was modified both on the development and the main branch. (A fake merge commit would probably cover this case, I guess, but not tested).
